"""empty message

Revision ID: 0a0970afc9cf
Revises: 89b8609ea127
Create Date: 2022-09-22 17:42:57.260625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0970afc9cf'
down_revision = '89b8609ea127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PATIENT', sa.Column('cardNum', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PATIENT', 'cardNum')
    # ### end Alembic commands ###
