"""empty message

Revision ID: 1978f168e8e4
Revises: 0a0970afc9cf
Create Date: 2022-09-23 08:15:45.361864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1978f168e8e4'
down_revision = '0a0970afc9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PATIENT', 'cardNum')
    op.drop_constraint('VITAL RECORDS_keeper_id_fkey', 'VITAL RECORDS', type_='foreignkey')
    op.create_foreign_key(None, 'VITAL RECORDS', 'USER', ['keeper_id'], ['public_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'VITAL RECORDS', type_='foreignkey')
    op.create_foreign_key('VITAL RECORDS_keeper_id_fkey', 'VITAL RECORDS', 'NURSE', ['keeper_id'], ['nurse_id'], ondelete='CASCADE')
    op.add_column('PATIENT', sa.Column('cardNum', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
