"""empty message

Revision ID: 3ae5f6baf7df
Revises: bcdc45dfc987
Create Date: 2022-09-28 22:41:40.769903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae5f6baf7df'
down_revision = 'bcdc45dfc987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DIAGNOSIS RECORDS', sa.Column('prescription', sa.Text(), nullable=True))
    op.drop_constraint('DIAGNOSIS RECORDS_keeper_id_fkey', 'DIAGNOSIS RECORDS', type_='foreignkey')
    op.create_foreign_key(None, 'DIAGNOSIS RECORDS', 'USER', ['keeper_id'], ['public_id'], ondelete='CASCADE')
    op.drop_column('DIAGNOSIS RECORDS', 'treatment_medification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DIAGNOSIS RECORDS', sa.Column('treatment_medification', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'DIAGNOSIS RECORDS', type_='foreignkey')
    op.create_foreign_key('DIAGNOSIS RECORDS_keeper_id_fkey', 'DIAGNOSIS RECORDS', 'DOCTOR', ['keeper_id'], ['doctor_id'], ondelete='CASCADE')
    op.drop_column('DIAGNOSIS RECORDS', 'prescription')
    # ### end Alembic commands ###
