"""empty message

Revision ID: 6946d61a71cc
Revises: 9d2da7b0083c
Create Date: 2022-09-22 17:34:26.422504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6946d61a71cc'
down_revision = '9d2da7b0083c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PATIENT', sa.Column('cardNum', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PATIENT', 'cardNum')
    # ### end Alembic commands ###
