"""empty message

Revision ID: 89b8609ea127
Revises: 41479fc85e91
Create Date: 2022-09-22 17:41:01.746868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b8609ea127'
down_revision = '41479fc85e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PATIENT', 'cardNum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PATIENT', sa.Column('cardNum', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
