"""empty message

Revision ID: 9d2da7b0083c
Revises: ab01b6c9f3a3
Create Date: 2022-09-22 17:32:02.073253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2da7b0083c'
down_revision = 'ab01b6c9f3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PATIENT', sa.Column('cardNum', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PATIENT', 'cardNum')
    # ### end Alembic commands ###
