"""empty message

Revision ID: ab01b6c9f3a3
Revises: 
Create Date: 2022-09-21 19:46:14.491516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab01b6c9f3a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AwaitingList')
    op.drop_constraint('ADMIN_public_id_fkey', 'ADMIN', type_='foreignkey')
    op.create_foreign_key(None, 'ADMIN', 'USER', ['public_id'], ['public_id'], ondelete='CASCADE')
    op.drop_constraint('DIAGNOSIS RECORDS_keeper_id_fkey', 'DIAGNOSIS RECORDS', type_='foreignkey')
    op.drop_constraint('DIAGNOSIS RECORDS_patient_id_fkey', 'DIAGNOSIS RECORDS', type_='foreignkey')
    op.create_foreign_key(None, 'DIAGNOSIS RECORDS', 'PATIENT', ['patient_id'], ['patient_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'DIAGNOSIS RECORDS', 'DOCTOR', ['keeper_id'], ['doctor_id'], ondelete='CASCADE')
    op.add_column('VITAL RECORDS', sa.Column('record_id', sa.Integer(), nullable=False))
    op.add_column('VITAL RECORDS', sa.Column('bloodpressure_mm', sa.Numeric(), nullable=True))
    op.add_column('VITAL RECORDS', sa.Column('bloodpressure_Hg', sa.Numeric(), nullable=True))
    op.drop_constraint('VITAL RECORDS_patient_id_fkey', 'VITAL RECORDS', type_='foreignkey')
    op.drop_constraint('VITAL RECORDS_keeper_id_fkey', 'VITAL RECORDS', type_='foreignkey')
    op.create_foreign_key(None, 'VITAL RECORDS', 'NURSE', ['keeper_id'], ['nurse_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'VITAL RECORDS', 'PATIENT', ['patient_id'], ['patient_id'], ondelete='CASCADE')
    op.drop_column('VITAL RECORDS', 'id')
    op.drop_column('VITAL RECORDS', 'blood_pressure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VITAL RECORDS', sa.Column('blood_pressure', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('VITAL RECORDS', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"VITAL RECORDS_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'VITAL RECORDS', type_='foreignkey')
    op.drop_constraint(None, 'VITAL RECORDS', type_='foreignkey')
    op.create_foreign_key('VITAL RECORDS_keeper_id_fkey', 'VITAL RECORDS', 'NURSE', ['keeper_id'], ['nurse_id'])
    op.create_foreign_key('VITAL RECORDS_patient_id_fkey', 'VITAL RECORDS', 'PATIENT', ['patient_id'], ['patient_id'])
    op.drop_column('VITAL RECORDS', 'bloodpressure_Hg')
    op.drop_column('VITAL RECORDS', 'bloodpressure_mm')
    op.drop_column('VITAL RECORDS', 'record_id')
    op.drop_constraint(None, 'DIAGNOSIS RECORDS', type_='foreignkey')
    op.drop_constraint(None, 'DIAGNOSIS RECORDS', type_='foreignkey')
    op.create_foreign_key('DIAGNOSIS RECORDS_patient_id_fkey', 'DIAGNOSIS RECORDS', 'PATIENT', ['patient_id'], ['patient_id'])
    op.create_foreign_key('DIAGNOSIS RECORDS_keeper_id_fkey', 'DIAGNOSIS RECORDS', 'DOCTOR', ['keeper_id'], ['doctor_id'])
    op.drop_constraint(None, 'ADMIN', type_='foreignkey')
    op.create_foreign_key('ADMIN_public_id_fkey', 'ADMIN', 'USER', ['public_id'], ['public_id'])
    op.create_table('AwaitingList',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"AwaitingList_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('other_names', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['PATIENT.patient_id'], name='AwaitingList_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='AwaitingList_pkey')
    )
    # ### end Alembic commands ###
