"""empty message

Revision ID: bcdc45dfc987
Revises: 1978f168e8e4
Create Date: 2022-09-28 02:12:22.497149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdc45dfc987'
down_revision = '1978f168e8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('DIAGNOSIS RECORDS_keeper_id_fkey', 'DIAGNOSIS RECORDS', type_='foreignkey')
    op.create_foreign_key(None, 'DIAGNOSIS RECORDS', 'USER', ['keeper_id'], ['public_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'DIAGNOSIS RECORDS', type_='foreignkey')
    op.create_foreign_key('DIAGNOSIS RECORDS_keeper_id_fkey', 'DIAGNOSIS RECORDS', 'DOCTOR', ['keeper_id'], ['doctor_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
