"""empty message

Revision ID: f72aa7a23983
Revises: 3ae5f6baf7df
Create Date: 2022-09-29 16:57:47.664336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72aa7a23983'
down_revision = '3ae5f6baf7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PendingList', sa.Column('gender', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PendingList', 'gender')
    # ### end Alembic commands ###
